#!/usr/bin/env bash

# This file is meant to be used to switch proxies for depending on host

if [[ $(hostname) != *.ihep.ac.cn ]];then
    ncat --proxy 127.0.0.1:8080 --proxy-type socks5 "$@" 
else
    echo "Skipping proxy for host $(hostname)"
    nc "$@"
fi
